# Generated by Django 5.0.6 on 2024-06-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Companies",
            new_name="Company",
        ),
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("pdf", models.FileField(upload_to="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_hackathon_api.company",
                    ),
                ),
            ],
        ),
    ]
