# Generated by Django 5.0.6 on 2024-06-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0003_alter_company_id_alter_companyreport_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreport",
            name="year",
            field=models.IntegerField(),
        ),
    ]
