# Generated by Django 5.0.6 on 2024-06-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0005_companyreport_pdf_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEmotions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("emotions", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_hackathon_api.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "company")},
            },
        ),
    ]
