# Generated by Django 5.0.6 on 2024-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0007_company_youtube_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyemotions",
            name="ai_gen_path",
            field=models.CharField(default="", max_length=200),
        ),
    ]
