# Generated by Django 5.0.6 on 2024-06-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0009_poststatus_role_tasktype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="is_good",
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_hackathon_api.sustainb3truser",
            ),
        ),
    ]
