# Generated by Django 5.0.6 on 2024-06-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0010_remove_company_is_good_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_hackathon_api.poststatus",
            ),
        ),
        migrations.AlterField(
            model_name="poststatus",
            name="status",
            field=models.CharField(default="pending", max_length=50, unique=True),
        ),
    ]
