# Generated by Django 5.0.6 on 2024-06-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_hackathon_api", "0012_post_img_bin_verified_post_img_waste_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAIStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img_bin_color", models.CharField(max_length=50)),
                ("img_bin_area", models.FloatField()),
                ("img_waste_prob", models.FloatField(null=True)),
                ("img_waste_classify", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="img_bin_verified",
        ),
        migrations.RemoveField(
            model_name="post",
            name="img_waste_verified",
        ),
        migrations.AddField(
            model_name="post",
            name="postAIStats",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_hackathon_api.postaistats",
            ),
        ),
    ]
